name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch System Dependencies
        run: sudo apt-get -y install jekyll texlive-latex-base

      - name: Fetch Website Dependencies
        run: bundle install --path vendor/bundle

      - name: Build Website
        shell: bash
        run: |
          make cv
          SPOTIFY_TOKEN="${{ secrets.SPOTIFYTOKEN }}" make site

      - name: Copy Repository via SCP
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "./_site/*"
          strip_components: 1
          rm: true
          target: "/var/www/markovejnovic"
