name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch System Dependencies
        run: sudo apt install jekyll -y

      - name: Fetch Website Dependencies
        run: bundle install --path vendor/bundle

      - name: Build Website
        env:
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
        run: bundle exec jekyll build

      - name: Copy Repository via SCP
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "./_site"
          target: "/var/www/markovejnovic"
